volumes:
  dvwa:


networks:
  dvwa:


services:
  dvwa:
    image: quwen/dvwa-dockerescape
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    container_name: dvwa
    # Change `always` to `build` to build from local source
    pull_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
